# MANDATORY: rules.yml file must be on the root folder such as <reponame>/semgrep/rules.yml to be called as ./semgrep/rules.yml

name: compliance

on: 
  workflow_call:

jobs:
  analyze:
    name: Semgrep Scan
    runs-on: ubuntu-latest
    container:
      image: returntocorp/semgrep
    if: (github.actor != 'dependabot[bot]')
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v4

      # Run the "semgrep ci" command on the command line of the docker image.
      - name: "Scan with semgrep"
        run: semgrep ci --verbose --metrics=off --sarif --output=semgrep-report.sarif --config=p/python --config=p/security-audit --config=p/secrets #--config=./semgrep/rules.yml
        continue-on-error: true
      - name: "Upload artifact"
        uses: actions/upload-artifact@v4
        with:
          name: Secrets SARIF file
          path: semgrep-report.sarif
          retention-days: 30
